# Generated by Django 5.2.9 on 2026-01-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('abuse', 'Harassment / abuse'), ('impersonation', 'Impersonation'), ('nudity', 'Inappropriate content'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_handled', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ur_status_created_idx'), models.Index(fields=['reported_user', '-created_at'], name='ur_reported_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='userreport_no_self'), models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'reported_user'), name='userreport_unique_open_report')],
            },
        ),
    ]
