# Generated by GitHub Copilot on 2026-01-07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0006_profile_private_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(max_length=2000)),
                ('page', models.CharField(blank=True, default='', max_length=300)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='support_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportenquiry',
            index=models.Index(fields=['status', '-created_at'], name='se_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='supportenquiry',
            index=models.Index(fields=['user', '-created_at'], name='se_user_created_idx'),
        ),
    ]
