# Generated by Django 5.2.9 on 2025-12-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_chatgroup_admin_chatgroup_groupchat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='code_room_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='is_code_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
    ]
