# Generated by Django 5.2.9 on 2025-12-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_chatgroup_code_room_name_chatgroup_is_code_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Private chat',
                'verbose_name_plural': 'Private chats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('a_rtchat.chatgroup',),
        ),
    ]
