# Generated by GitHub Copilot

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0007_remove_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
