# Generated by GitHub Copilot on 2026-01-01

from django.db import migrations


def seed_default_groupchats(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')

    # base_name is used for loose matching so existing emoji variants don't get duplicated.
    defaults = [
        # 🚀 Tech & Coding
        ('Code & Coffee', 'Code & Coffee ☕'),
        ('The Syntax Squad', 'The Syntax Squad'),
        ('Bug Hunters', 'Bug Hunters 🐞'),
        ('FullStack Circle', 'FullStack Circle'),

        # 🤝 Professional & Indian Vibes
        ('Indian-Boys', 'Indian-Boys 🔪👻'),
        ('The Nexus', 'The Nexus'),
        ('Growth Mindset', 'Growth Mindset'),

        # ✨ Social & Fun
        ('Backbenchers', 'Backbenchers 😎'),
        ('Vibe Check', 'Vibe Check ⚡'),
        ('Nalayak Gang', 'Nalayak Gang 🤡'),
        ('Girls Group', 'Girls Group 💅✨'),
        ('Late Night Owls', 'Late Night Owls 🦉'),

        # 📢 Promotion (no uploads, but links allowed)
        ('Free Promotion', 'Free Promotion 📢'),
    ]

    for base, display in defaults:
        base_l = base.lower()
        # If a room already exists with either group_name or groupchat_name containing the base,
        # don't create another one.
        exists = (
            ChatGroup.objects.filter(group_name__icontains=base_l).exists()
            or ChatGroup.objects.filter(groupchat_name__icontains=base_l).exists()
        )
        if exists:
            continue

        ChatGroup.objects.create(
            group_name=display,
            groupchat_name=display,
            is_private=False,
            is_code_room=False,
        )


def unseed_default_groupchats(apps, schema_editor):
    """Best-effort reverse: remove only the rooms we created by exact group_name match."""
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    names = [
        'Code & Coffee ☕',
        'The Syntax Squad',
        'Bug Hunters 🐞',
        'FullStack Circle',
        'Indian-Boys 🔪👻',
        'The Nexus',
        'Growth Mindset',
        'Backbenchers 😎',
        'Vibe Check ⚡',
        'Nalayak Gang 🤡',
        'Girls Group 💅✨',
        'Late Night Owls 🦉',
        'Free Promotion 📢',
    ]
    ChatGroup.objects.filter(group_name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0012_messagereaction_readd'),
    ]

    operations = [
        migrations.RunPython(seed_default_groupchats, reverse_code=unseed_default_groupchats),
    ]
