# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations
from django.db.models import Q


def update_default_groupchats(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')

    # Remove unwanted default rooms (best-effort substring match so emoji variants are covered).
    unwanted_bases = [
        'Nalayak Gang',
        'Indian-Boys',
        'Girls Group',
        'The Nexus',
        'The Syntax Squad',
    ]

    for base in unwanted_bases:
        ChatGroup.objects.filter(
            Q(group_name__icontains=base) | Q(groupchat_name__icontains=base)
        ).delete()

    # Add new default rooms.
    new_bases = [
        'Showcase Your Work',
        'Job & Internships',
        'Meme Central',
    ]

    for base in new_bases:
        exists = ChatGroup.objects.filter(
            Q(group_name__icontains=base) | Q(groupchat_name__icontains=base)
        ).exists()
        if exists:
            continue

        ChatGroup.objects.create(
            group_name=base,
            groupchat_name=base,
            is_private=False,
            is_code_room=False,
        )


def reverse_update_default_groupchats(apps, schema_editor):
    """Best-effort reverse: remove only the rooms this migration adds."""
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')

    new_bases = [
        'Showcase Your Work',
        'Job & Internships',
        'Meme Central',
    ]

    for base in new_bases:
        ChatGroup.objects.filter(
            Q(group_name__icontains=base) | Q(groupchat_name__icontains=base)
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0016_chat_read_state'),
    ]

    operations = [
        migrations.RunPython(update_default_groupchats, reverse_code=reverse_update_default_groupchats),
    ]
