# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations, models


SHOWCASE_GROUP_NAME = 'Showcase Your Work'
OLD_SHOWCASE_BASE = 'Project Showcase'


PINNED_TEMPLATE = (
    "🚀 Project Name: (e.g., Vixogram)\n"
    "🛠 Tech Used: (e.g., Django, Redis, PostgreSQL)\n"
    "🔗 Link: (GitHub ya Live URL)\n"
    "📸 Screenshot/Video: (Niche attach karein)\n"
    "❓ What I need: (Feedback / Beta Testers / Stars)"
)


def _rename_or_merge_showcase(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    GroupMessage = apps.get_model('a_rtchat', 'GroupMessage')
    ChatReadState = apps.get_model('a_rtchat', 'ChatReadState')
    ModerationEvent = apps.get_model('a_rtchat', 'ModerationEvent')

    showcase = ChatGroup.objects.filter(group_name__icontains=SHOWCASE_GROUP_NAME).first()
    old = ChatGroup.objects.filter(group_name__icontains=OLD_SHOWCASE_BASE).first()
    if not old:
        old = ChatGroup.objects.filter(groupchat_name__icontains=OLD_SHOWCASE_BASE).first()

    if showcase and old and showcase.id != old.id:
        # Move references over, then delete the old room.
        GroupMessage.objects.filter(group_id=old.id).update(group_id=showcase.id)
        ChatReadState.objects.filter(group_id=old.id).update(group_id=showcase.id)
        ModerationEvent.objects.filter(room_id=old.id).update(room_id=showcase.id)
        try:
            showcase.members.add(*list(old.members.all()))
        except Exception:
            pass
        old.delete()

    if not showcase:
        if old:
            # Rename the existing room.
            old.group_name = SHOWCASE_GROUP_NAME
            old.groupchat_name = SHOWCASE_GROUP_NAME
            old.save(update_fields=['group_name', 'groupchat_name'])
            showcase = old
        else:
            showcase = ChatGroup.objects.create(
                group_name=SHOWCASE_GROUP_NAME,
                groupchat_name=SHOWCASE_GROUP_NAME,
                is_private=False,
                is_code_room=False,
            )

    # Set/update pinned template.
    try:
        showcase.pinned_message = PINNED_TEMPLATE
        showcase.save(update_fields=['pinned_message'])
    except Exception:
        pass


def _reverse_unset_pin(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    qs = ChatGroup.objects.filter(group_name__icontains=SHOWCASE_GROUP_NAME)
    for g in qs:
        try:
            if (g.pinned_message or '') == PINNED_TEMPLATE:
                g.pinned_message = ''
                g.save(update_fields=['pinned_message'])
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0017_update_default_groupchats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='pinned_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='link_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='link_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='link_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='link_site_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(_rename_or_merge_showcase, reverse_code=_reverse_unset_pin),
    ]
