# Generated by GitHub Copilot on 2026-01-09

from django.db import migrations


def add_free_promotion_group(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')

    # Check if already exists
    base = 'free promotion'
    exists = (
        ChatGroup.objects.filter(group_name__icontains=base).exists()
        or ChatGroup.objects.filter(groupchat_name__icontains=base).exists()
    )
    if exists:
        return

    ChatGroup.objects.create(
        group_name='Free Promotion 📢',
        groupchat_name='Free Promotion 📢',
        is_private=False,
        is_code_room=False,
    )


def remove_free_promotion_group(apps, schema_editor):
    """Reverse: remove the group."""
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    ChatGroup.objects.filter(group_name='Free Promotion 📢').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0018_showcase_pin_and_link_preview'),
    ]

    operations = [
        migrations.RunPython(add_free_promotion_group, reverse_code=remove_free_promotion_group),
    ]
