# Generated by GitHub Copilot on 2026-01-09

from django.db import migrations


SHOWCASE_GROUP_NAME = 'Showcase Your Work'

PINNED_TEMPLATE_EN = (
    "🚀 Project Name: (e.g., Vixogram)\n"
    "🛠 Tech Used: (e.g., Django, Redis, PostgreSQL)\n"
    "🔗 Link: (GitHub or Live URL)\n"
    "📸 Screenshot/Video: (Attach below)\n"
    "❓ What I need: (Feedback / Beta testers / Stars)"
)


def set_showcase_pin_english(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    qs = ChatGroup.objects.filter(group_name__icontains=SHOWCASE_GROUP_NAME)
    if not qs.exists():
        qs = ChatGroup.objects.filter(groupchat_name__icontains=SHOWCASE_GROUP_NAME)

    for g in qs:
        try:
            g.pinned_message = PINNED_TEMPLATE_EN
            g.save(update_fields=['pinned_message'])
        except Exception:
            continue


def reverse_unset_english_pin(apps, schema_editor):
    ChatGroup = apps.get_model('a_rtchat', 'ChatGroup')
    qs = ChatGroup.objects.filter(group_name__icontains=SHOWCASE_GROUP_NAME)
    if not qs.exists():
        qs = ChatGroup.objects.filter(groupchat_name__icontains=SHOWCASE_GROUP_NAME)

    for g in qs:
        try:
            if (g.pinned_message or '') == PINNED_TEMPLATE_EN:
                g.pinned_message = ''
                g.save(update_fields=['pinned_message'])
        except Exception:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0019_add_free_promotion_group'),
    ]

    operations = [
        migrations.RunPython(set_showcase_pin_english, reverse_code=reverse_unset_english_pin),
    ]
