# Generated by Django 5.2.9 on 2026-01-23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0027_code_room_join_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderoomjoinrequest',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='coderoomjoinrequest',
            index=models.Index(fields=['room', 'admitted_at', '-last_seen_at'], name='crjr_room_status_seen_idx'),
        ),
    ]
